version: "3.8"
services:
  bot:
    build: .
    container_name: birthy_bot
    restart: "unless-stopped"
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    depends_on:
      - database

  database:
    image: postgres:14.1-alpine
    container_name: birthy_database
    restart: "unless-stopped"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - volume:/data/postgres

volumes:
  volume:
