version: "3.8"
services:
  database:
    user: root
    image: postgres:14.1-alpine
    container_name: birthy_database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./database/:/var/lib/postgresql/data
    networks:
      database_network:
        aliases:
          - database
        ipv4_address: "155.0.0.8"
  pgadmin:
    user: root
    image: dpage/pgadmin4
    container_name: birthy_pgadmin
    restart: unless-stopped
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin/:/var/lib/pgadmin
    networks:
      database_network:
        aliases:
          - pgadmin
        ipv4_address: "155.0.0.9"

volumes:
  database:
  pgadmin:

networks:
  database_network:
    ipam:
      config:
        - subnet: 155.0.0.0/24
